###########
# Classifier #
###########
seed: 1234

imgpath: ''
output_dir: 'Output'
# Required columns: (lesion_id, image_id) or names, 
data_file: '/jet/home/nmurali/asc170022p/nmurali/projects/augmentation_by_explanation_eccv22/Data/dirty_mnist_train.csv'
data_file_test: '/jet/home/nmurali/asc170022p/nmurali/projects/augmentation_by_explanation_eccv22/Data/dirty_mnist_val.csv'
class_names: '0,1,2,3,4,5,6'
size: 64
dataset: 'Dirty_MNIST'
mixUp: False
labelSmoothing: False
focalLoss: False
num_classes: 7
drop_rate: 0.00
num_epochs: 25
batch_size: 64
model: 'densenet121'
opt: 'adam'
channel: 1
cuda: True
shuffle: True
lr: 0.0001
threads: 4
taskweights: False
featurereg: False
weightreg: False
data_aug_hf: 0.5
# hyper-parameter for mix-up and label smoothing
alpha: 0.2
multi_class: True

# hyper-parameter while saving the classifier output: TEST
ckpt_name: ''
partition_name: ["test"]
TS: True
