###########
# Classifier #
###########
seed: 1234

output_dir: 'Output'
data_file: '/jet/home/nmurali/asc170022p/nmurali/projects/augmentation_by_explanation_eccv22/Data/afhq.csv'
column_name_split: 'split1'
class_names: 'cat,dog'
num_classes: 2
size: 256
dataset: 'AFHQ'
mixUp: False
labelSmoothing: False
focalLoss: False
drop_rate: 0.00
num_epochs: 25
batch_size: 64
model: 'densenet169'
opt: 'adam'
channel: 3
cuda: True
shuffle: True
lr: 0.001
threads: 4
taskweights: True
featurereg: False
weightreg: False
data_aug_hf: 0.5
# hyper-parameter for mix-up and label smoothing
alpha: 0.2
multi_class: True


# hyper-parameter while saving the classifier output: TEST
ckpt_name: ''
partition_name: ["test", "train"]
TS: True