###########
# Classifier #
###########
seed: 0
imgpath: '/ocean/projects/asc170022p/singla/Datasets/celebA/images/'
output_dir: 'Output'
data_file: '/jet/home/nmurali/asc170022p/nmurali/projects/augmentation_by_explanation_eccv22/Data/celeba.csv'
column_name_split: 'val_train_test'
class_names: 'Young,Smiling'
size: 256
center_crop: 190
dataset: 'CelebA'
mixUp: False
labelSmoothing: False
focalLoss: False
num_classes: 2
drop_rate: 0.00
num_epochs: 25
batch_size: 64
model: 'densenet121'
opt: 'adam'
channel: 3
cuda: True
shuffle: True
lr: 0.001
threads: 4
taskweights: True
featurereg: False
weightreg: False
data_aug_hf: 0.5
# hyper-parameter for mix-up and label smoothing
alpha: 0.2
multi_class: False
# its multi-label, so calculate ECE per class


# hyper-parameter while saving the classifier output: TEST
ckpt_name: ''
partition_name: ["test"]
TS: True