###########
# Classifier #
###########

# user hyperparams
ckpt_name: '/jet/home/nmurali/asc170022p/nmurali/projects/augmentation_by_explanation_eccv22/Output/ACE/da_skin_ln0p50/augmented_data/e_10_mix_ratio_0.5_fold1.pt'

seed: 0
imgpath: '/ocean/projects/asc170022p/singla/Datasets/HAM10000/imgs'
output_dir: 'Output'
# Required columns: (lesion_id, image_id) or names, 
data_file: '/jet/home/nmurali/asc170022p/nmurali/projects/augmentation_by_explanation_eccv22/Data/skin.csv'
column_name_split: 'test_train'
class_names: 'nv,mel_or_bkl'
size: 256
dataset: 'HAM'
mixUp: False
labelSmoothing: False
focalLoss: False
num_classes: 2
drop_rate: 0.00
num_epochs: 40
batch_size: 64
model: 'densenet169'
opt: 'adam'
channel: 3
cuda: True
shuffle: True
lr: 0.001
threads: 4
taskweights: True
featurereg: False
weightreg: False
data_aug_hf: 0.5
# hyper-parameter for mix-up and label smoothing
alpha: 0.2
multi_class: True

# hyper-parameter while saving the classifier output: TEST
partition_name: ["test"]
TS: True
