###########
# Classifier #
###########

# user hyperparams
ckpt_name: '/jet/home/nmurali/asc170022p/nmurali/projects/augmentation_by_explanation_eccv22/Output/AFHQ/Classifier_Seed_1234_Dropout_0.0_LS_False_MU_False_FL_False_s0p0/AFHQ-densenet169-AFHQ_256-best-auc1.0000.pt'

seed: 1234
output_dir: 'Output'
data_file: '/jet/home/nmurali/asc170022p/nmurali/projects/augmentation_by_explanation_eccv22/Data/afhq.csv'
column_name_split: 'train'
class_names: 'cat,dog'
num_classes: 2
size: 256
dataset: 'AFHQ'
mixUp: False
labelSmoothing: False
focalLoss: False
drop_rate: 0.00
num_epochs: 25
batch_size: 64
model: 'densenet169'
opt: 'adam'
channel: 3
cuda: True
shuffle: True
lr: 0.001
threads: 4
taskweights: True
featurereg: False
weightreg: False
data_aug_hf: 0.5
# hyper-parameter for mix-up and label smoothing
alpha: 0.2
multi_class: True


# hyper-parameter while saving the classifier output: TEST
partition_name: ["test"]
TS: True